series: Basic C++
title: Functions
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use functions to wrap useful code.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Data Types